# 高级设置的泛匹配中，不接收邮件的玩家名
blacklist-players: []

# 是否能向自己发送邮件
can-send-to-yourself: false

# BungeeCord 广播设置
bungeecord:
  # 是否启用 BungeeCord 跨服通知新邮件 发送与接收
  enable: true
  # 发送方标识码，用于识别消息来源
  sender-key: 'default'
  # 接收方标识码，接收到的消息的标识码中包含该标识码才真正接收并通知相关玩家
  # 如，发送方标识码为 'server1,server2,'
  # 子服1的接收方标识码为 'server1,' 则它可以接收消息
  # 子服2的接收方标识码为 'server3,' 则它不接收消息
  receiver-key: 'default'

default:
  title: '未命名邮件'
# 预设图标，不能写 custom，不能以英文感叹号开头
preset-icons:
  # default 为默认图标，必须要有默认图标
  default:
    display: '默认'
    item: PAPER
  example:
    display: '示例1'
    # 使用 MythicMobs 物品作为图标 (草稿菜单显示mm物品名，收件箱发件箱中仅使用物品、CustomModelData、附魔、染色数据，不使用名字和 Lore)
    item: mythic-示例
  example1:
    display: '示例2'
    # 使用 ItemsAdder 物品作为图标，显示策略同 MythicMobs 图标
    item: itemsadder-示例

# 帮助命令
help:
  player:
    - '&e&l邮件系统 &8<必选参数> [可选参数]'
    - '  &f/mail draft &8-- &3创建或编辑一个草稿'
    - '  &f/mail outbox &8-- &3打开发件箱'
    - '  &f/mail inbox &7[&fall&7/&funread&7] &8-- &3打开收件箱&7(默认打开未读)'
  admin:
    - '&c管理员命令'
    - '  &f/mail outbox <玩家> &8-- &e为某人打开发件箱'
    - '  &f/mail inbox <all/unread> <玩家> &8-- &e为某人打开收件箱'
    - '  &f/mail admin outbox <玩家> &8-- &e打开某玩家的发件箱'
    - '  &f/mail admin inbox <all/unread> <玩家> &8-- &e打开某玩家的收件箱'
    - '  &f/mail reload database &8-- &3重载数据库'
    - '  &f/mail reload &8-- &3重载配置文件'

# 提示消息 (待定)
messages:
  prefix: '&7[&e&l邮件&7] &a'
  command:
    reload: '配置文件已重载 &7(如需重载数据库，请使用 &f/mail reload database&7)'
    reload-database: '数据库配置已重载，已重新连接数据库'
  date-time: 'yyyy年MM月dd日 HH:mm:ss'
  draft:
    selected-icon-lore:
      - '&a&l已选择'
    no-receivers: '&e你没有设置接收者，无法发送邮件!'
    cant-send-to-yourself: '&e你不能发送邮件给你自己!'
    attachments:
      remove-lore:
        - ''
        - '&a左键 &7| &f删除并取出该附件'
      money:
        icon: GOLD_NUGGET
        name: '&e&l金币'
        lore:
          - ''
          - '  &f数量: &e%money%'
      item:
        display: '%item%'
        display-with-amount: '%item%&7 x%amount%'
    sent: '邮件发送成功!'
  inbox:
    attachments-fail: '有附件领取失败! 请联系管理员查看后台了解详细'
  join:
    text: '&e你有 &b%count% &e封未读邮件 &7[&a点击查看&7]'
    text-online: '&e你有一封新的未读邮件 &7[&a点击查看&7]'
    hover:
      - '&e点击打开收件箱'
    command: '/mail inbox unread'
