# 高级设置的泛匹配中，不接收邮件的玩家名
blacklist-players: []

# 是否能向自己发送邮件
can-send-to-yourself: false

# 是否使用 uuid 而非玩家名来识别玩家
# 离线模式服务器不推荐启用该选项
# auto - 自动 根据当前服务器的模式决定
# true - 在线模式 使用uuid识别玩家
# false - 离线模式 使用玩家名识别玩家
###########################################
#### 危险 : 插件正式投入使用后，请勿修改该选项
#### 否则将出现不可预料的问题。
###########################################
online-mode: auto

# BungeeCord 广播设置
bungeecord:
  # 是否启用 BungeeCord 跨服通知新邮件 发送与接收
  enable: true
  # 发送方标识码，用于识别消息来源
  sender-key: 'default'
  # 接收方标识码，接收到的消息的标识码中包含该标识码才真正接收并通知相关玩家
  # 如，发送方标识码为 'server1,server2,'
  # 子服1的接收方标识码为 'server1,' 则它可以接收消息
  # 子服2的接收方标识码为 'server3,' 则它不接收消息
  receiver-key: 'default'

# 收纳袋图标最多显示的物品数量
bundle-max-slots: 7

default:
  title: '未命名邮件'
# 预设图标，不能写 custom，不能以英文感叹号开头
preset-icons:
  # default 为默认图标，必须要有默认图标
  default:
    display: '默认'
    item: BUNDLE
  example:
    display: '示例1'
    # 使用 MythicMobs 物品作为图标 (草稿菜单显示mm物品名，收件箱发件箱中仅使用物品、CustomModelData、附魔、染色数据，不使用名字和 Lore)
    item: mythic-示例
  example1:
    display: '示例2'
    # 使用 ItemsAdder 物品作为图标，显示策略同 MythicMobs 图标
    item: itemsadder-示例

# 各权限发邮件所需要花费的金币
# 权限为 sweetmail.price.键，如 sweetmail.price.default
# 价格低的检查优先级最高
# 无法获取到价格或价格为0时不收取金币
# 玩家默认拥有 default 权限
price:
  default: 100
  vip: 80
  svip: 50
  mvp: 30

# 各权限发送邮件，附件的有效时间 (天)
# 权限为 sweetmail.outdate.键，如 sweetmail.outdate.default
# 时间长的检查优先级最高，特别地，小于等于0的优先级更高
# 无法获取到有效时间或时间小于0时永不过期
# 玩家默认拥有 default 权限
outdate-time:
  default: 7
  vip: 9
  svip: 12
  mvp: 14

# 各权限的草稿能保存的时间 (小时)
# 权限为 sweetmail.draft.outdate.键，如 sweetmail.draft.outdate.default
# 拥有权限 sweetmail.draft.bypass.outdate 者可永久保存
# 玩家在打开草稿编辑器时，会提示可保存时间
# 玩家下次打开草稿编辑器时如果与上次打开时间相差超过此处设定的值，则重置草稿
# 每次打开草稿编辑器，都会重置一次可保存时间，举个例子
# 默认值为 24 小时，玩家在 8:00 打开了草稿编辑器，次日 8:00 过期
# 如果玩家之后又在 10:00 打开了草稿编辑器，那么变为次日 10:00 过期
# 无法获取到有效时间或时间小于等于0时永不过期
# 玩家默认拥有 default 权限
outdate-draft:
  default: 10
  vip: 12
  svip: 24
  mvp: 24

# 内置附件类型设置
attachments:
  item:
    # 物品附件不允许添加的 材质、物品名、Lore 内容
    # 除了材质外，均为「包含」匹配
    # 如 display_name 设为 [ '11', '22' ]，则不允许名字包含 11 或 22 的物品
    # 如 lore 设为 [ '33', '44' ]，则不允许Lore包含 33 或 44 的物品
    # 例外: 如果其中有一项为 *，则全部不允许
    # 如 display_name 设为 [ '*' ]，则不允许所有拥有自定义名字的物品
    # 如 lore 设为 [ '*' ]，则不允许所有拥有Lore的物品
    # 例外: 如果其中有一项为空字符串，则不允许名字或lore不存在
    # 如 display_name 设为 [ '', '11' ]，则不允许没有名字，或者名字包含 11 的物品，名字包含 22 的物品是允许的，空字符串不参与后续判定
    # 如 lore 设为 [ '', '33' ]，则不允许没有Lore，或者Lore包含 11 的物品，名字包含 22 的物品是允许的，空字符串不参与后续判定
    blacklist:
      materials: []
      display_name: []
      lore: []

# 帮助命令
help:
  player:
    - '&e&l邮件系统 &8<必选参数> [可选参数]'
    - '  &f/mail draft &8-- &3创建或编辑一个草稿'
    - '  &f/mail outbox &8-- &3打开发件箱'
    - '  &f/mail inbox &7[&fall&7/&funread&7] &8-- &3打开收件箱&7(默认打开未读)'
  admin:
    - '&c管理员命令'
    - '  &f/mail outbox <玩家> &8-- &e为某人打开发件箱'
    - '  &f/mail inbox <all/unread> <玩家> &8-- &e为某人打开收件箱'
    - '  &f/mail admin outbox <玩家> &8-- &e打开某玩家的发件箱'
    - '  &f/mail admin inbox <all/unread> <玩家> &8-- &e打开某玩家的收件箱'
    - '  &f/mail admin timed <定时序列> &8-- &e查看定时发送邮件序列简要信息'
    - '  &f/mail admin cancel <定时序列> &8-- &e取消定时发送邮件序列'
    - '  &f/mail reload database &8-- &3重载数据库'
    - '  &f/mail reload &8-- &3重载配置文件'

# 提示消息 (待定)
messages:
  prefix: '&7[&e&l邮件&7] &a'
  command:
    reload: '配置文件已重载 &7(如需重载数据库，请使用 &f/mail reload database&7)'
    reload-database: '数据库配置已重载，已重新连接数据库'
    timed:
      info:
        display:
          - '&f定时发送序列: &e%id%'
          - '&f发送人: &e%sender%'
          - '&f发送人显示: &e%senderDisplay%'
          - '&f收件人: &e%receiver%'
          - '&f泛收件人: &e%advReceivers%'
          - '&b其它信息请到 timed_draft.yml 查看'
        not-found: '&c找不到定时发送序列 &e%id%'
      cancel:
        success: '成功取消定时发送序列 &e%id%'
        fail: '&c找不到定时发送序列 &e%id%'
  date-time: 'yyyy年MM月dd日 HH:mm:ss'
  draft:
    online:
      no-player: '&e找不到该玩家'
    no-money: '&e你没有足够的金币&7(%price%)&e去发送邮件'
    money-format: '%.1f'
    selected-icon-lore:
      - '&a&l已选择'
    no-receivers: '&e你没有设置接收者，无法发送邮件!'
    cant-send-to-yourself: '&e你不能发送邮件给你自己!'
    open-tips: '&f你的草稿将会保存 &e%hours% &f小时，在&e %time% &f过期，请勿在附件存放贵重物品。草稿过期时间会在重新打开草稿编辑器时刷新。'
    attachments:
      remove-lore:
        - ''
        - '&a左键 &7| &f删除并取出该附件'
      remove-lore-admin:
        - ''
        - '&a左键 &7| &f删除并取出该附件'
        - '&eShift+左键 &7| &f删除'
      money:
        icon: GOLD_NUGGET
        name: '&e&l金币'
        lore:
          - ''
          - '  &f数量: &e%money%'
        add:
          prompt-tips: '&7[&e&l邮件&7] &b请在聊天栏发送&e“附件金币数量”&b的值 &7(输入 &ccancel &7取消添加附件)'
          prompt-cancel: 'cancel'
          fail: '&7[&e&l邮件&7] &e请输入大于0的实数'
          not-enough: '&7[&e&l邮件&7] &e你没有足够的金币'
      item:
        display: '%item%'
        display-with-amount: '%item%&7 x%amount%'
        banned: '&e禁止添加该物品到附件'
      command:
        prompt-tips: '&7[&e&l邮件&7] &b请在聊天栏发送&e“控制台命令附件”&b的值 &7(格式 &f图标,显示名称,执行命令&7，如&f PAPER,10金币,money give %player_name% 10 &7。输入 &ccancel &7取消添加附件)'
        prompt-cancel: 'cancel'
        fail: '&7[&e&l邮件&7] &e格式不正确，应为 &f图标,显示名称,执行命令&e，如&f PAPER,10金币,money give %player_name% 10'
      use-illegal-deny: '&b附件 &e%name% &b的数据不合规，无法领取，请联系管理员。'
    send-with-adv-receivers: '正在发送邮件… &f发送所需时间可能会比较长，请耐心等待，这由服务器的玩家总数决定。'
    sent: '邮件发送成功!'
  inbox:
    attachments-outdated: '&e该邮件的附件已过期，无法领取'
    attachments-fail: '&e有附件领取失败! 请联系管理员查看后台了解详细'
  join:
    text: '&e你有 &b%count% &e封未读邮件 &7[&a点击查看&7]'
    text-online: '&e你有一封新的未读邮件 &7[&a点击查看&7]'
    hover:
      - '&e点击打开收件箱'
    command: '/mail inbox unread'
